name: planet_photo_tracker
description: A Flutter app to capture field data with GPS overlays.
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  geolocator: ^13.0.2
  share_plus: ^10.1.4
  path_provider: ^2.0.10
  shared_preferences: ^2.0.10
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

